name: TPK Updater

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install deps
      run: |
        pip install --upgrade pip
        pip install selectolax playwright httpx[http2] pytz GitPython

    - name: Run script
      env:
        TPK_BASE_URL: ${{ secrets.TPK_BASE_URL }}
      run: |
        python -m tpk.py

    - name: Force push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit --allow-empty -m "TPK auto $(date -u '+%Y-%m-%d %H:%M')" 
        git push origin main --force-with-lease
